const fs = require('node:fs');
const {
  extractChapterRef,
  formatMarkdownTable,
  getVisualizationSummarySections,
  replaceAutoGeneratedBlock,
  writeMarkdownFile
} = require('./lib.ts');

const graph = JSON.parse(fs.readFileSync('generated/graph.json', 'utf8'));
const nodeByFile = new Map(graph.nodes.filter((node) => node.file).map((node) => [node.file, node]));
const sections = getVisualizationSummarySections();

const getSection = (prefix) => sections.find((section) => section.title.startsWith(prefix));
const secondPart = getSection('第二部分');
const toolEntries = (secondPart?.entries || []).filter((entry) => entry.filePath === 'part-2/chapter-4-claude-manual.md' || entry.filePath.startsWith('part-2/chapter-4-'));
const comparisonEntries = (secondPart?.entries || []).filter((entry) => !toolEntries.some((item) => item.filePath === entry.filePath));

const stages = [
  {
    label: '0. 认知校准',
    entries: getSection('第一部分')?.entries || [],
    capabilityGoal: '建立 AI 编程心智模型，理解“助手”与“Agent”的边界',
    deliverable: '一份个人使用边界清单（适用/不适用场景）'
  },
  {
    label: '1. 工具掌握',
    entries: toolEntries,
    capabilityGoal: '熟悉 Claude Code 的命令、上下文、技能、GitHub 集成与高级功能',
    deliverable: '一套可复用的 `.claude/` 最小配置'
  },
  {
    label: '2. 多工具横向扩展',
    entries: comparisonEntries,
    capabilityGoal: '建立多模型/多工具选型能力与迁移能力',
    deliverable: '一张“任务类型 → 推荐工具”映射表'
  },
  {
    label: '3. 工程化提效',
    entries: getSection('第三部分')?.entries || [],
    capabilityGoal: '把提示工程、测试、调试流程整合到开发闭环',
    deliverable: '一个端到端小项目（含测试和回归）'
  },
  {
    label: '4. Agent 系统构建',
    entries: getSection('第四部分')?.entries || [],
    capabilityGoal: '从单 Agent 走向任务系统、后台执行与多智能体协作',
    deliverable: '一套可运行的 Agent 原型（含任务/后台/协作）'
  },
  {
    label: '5. 组织级演进',
    entries: getSection('第五部分')?.entries || [],
    capabilityGoal: '从个人提效升级到团队级软件交付能力',
    deliverable: '一份团队落地路线图（治理、触发器、扩展策略）'
  },
  {
    label: '6. 参考与持续更新',
    entries: getSection('附录')?.entries || [],
    capabilityGoal: '建立工具与资源的持续学习机制',
    deliverable: '个人知识库与更新节奏'
  }
].filter((stage) => stage.entries.length > 0);

function buildRefMap(entries) {
  const baseRefs = entries.map((entry) => extractChapterRef(entry.title));
  const counts = new Map();
  baseRefs.forEach((ref) => counts.set(ref, (counts.get(ref) || 0) + 1));

  return new Map(entries.map((entry) => {
    const baseRef = extractChapterRef(entry.title);
    if ((counts.get(baseRef) || 0) === 1) return [entry.filePath, baseRef];

    const suffixSource = entry.title.split(/[:：]/).slice(1).join(':').trim() || entry.sectionTitle;
    const suffix = suffixSource.split(/[——-]/)[0].trim().slice(0, 8);
    return [entry.filePath, `${baseRef}（${suffix}）`];
  }));
}

function inferTags(entry, node) {
  const tags = [];
  const title = entry.title;
  const layer = (node?.metadata?.architecture_layer || [])[0];

  if (layer === 'foundations') tags.push('research');
  if (layer === 'models-and-tools') tags.push('tooling');
  if (layer === 'workflows-and-practices') tags.push('workflow');
  if (layer === 'systems-and-governance') tags.push('system', 'org');
  if (entry.filePath.startsWith('appendix/')) tags.push('research');

  if (/(Prompt|上下文|Workflow|测试|调试|实战|复盘)/.test(title)) tags.push('workflow');
  if (/(Agent|系统|架构|Trellis|Harness|治理)/.test(title)) tags.push('system');
  if (/(组织|团队|复盘|怀疑者|Codex 的威力)/.test(title)) tags.push('org');

  return Array.from(new Set(tags)).slice(0, 3);
}

const allEntries = stages.flatMap((stage) => stage.entries);
const refMap = buildRefMap(allEntries);
const stageRows = stages.map((stage) => [
  stage.label,
  stage.entries.map((entry) => refMap.get(entry.filePath)).join('、'),
  stage.capabilityGoal,
  stage.deliverable
]);
const chapterRefs = allEntries.map((entry) => refMap.get(entry.filePath));
const chapterRows = allEntries.map((entry) => {
  const node = nodeByFile.get(entry.filePath);
  return [refMap.get(entry.filePath), inferTags(entry, node).map((tag) => `\`${tag}\``).join(', ')];
});

const matrixRows = stages.map((stage) => {
  const refs = new Set(stage.entries.map((entry) => refMap.get(entry.filePath)));
  return [stage.label, ...chapterRefs.map((ref) => (refs.has(ref) ? '●' : ''))];
});

const autoBlockLines = [
  '## 全书时间线（按能力跃迁）',
  '',
  ...formatMarkdownTable(['阶段', '精确章节清单', '能力目标', '建议产出'], stageRows),
  '',
  '## 章节标签索引（自动推断）',
  '',
  '> 标签体系沿用原始可视化页的 `tooling`、`workflow`、`system`、`org`、`research`，当前按章节分层与标题关键词自动推断。',
  '',
  ...formatMarkdownTable(['章节', '主标签'], chapterRows),
  '',
  '## 章节索引矩阵（阅读阶段 × 章节号）',
  '',
  '> 列为章节号，行为阅读阶段。`●` 表示该章属于该阶段。',
  '',
  ...formatMarkdownTable(['阅读阶段 \\ 章节号', ...chapterRefs], matrixRows),
  '',
  '## 角色路径（最短路线）',
  '',
  '- 工程师路径：1. 工具掌握 → 3. 工程化提效 → 4. Agent 系统构建。',
  '- 产品路径：0. 认知校准 → 2. 多工具横向扩展 → 5. 组织级演进。',
  '- 设计路径：0. 认知校准 → 3. 工程化提效 → 4. Agent 系统构建。',
  '- 平台路径：1. 工具掌握 → 4. Agent 系统构建 → 5. 组织级演进。',
  '',
  '## 维护约束（避免索引失配）',
  '',
  '后续新增或调整章节时，必须在同一个 PR 内同步更新以下三处：',
  '',
  '1. `SUMMARY.md`（目录与链接）；',
  '2. `visualizations/timeline-overview.md`（原始展示模式定义）；',
  '3. `visualizations/architecture-overview.md`（架构模式定义与配套矩阵）。',
  ''
];

replaceAutoGeneratedBlock('visualizations/timeline-overview.md', 'TIMELINE', autoBlockLines);

writeMarkdownFile('generated/timeline.md', [
  '# 学习路径时间线（自动生成）',
  '',
  '> 本页与 `/visualizations/timeline-overview` 共享同一份自动生成内容。',
  '',
  '<TimelineVisualization />',
  '',
  ...autoBlockLines
]);

console.log('generated/timeline.md created');
