const fs = require('node:fs');
const {
  extractChapterRef,
  formatMarkdownTable,
  getVisualizationSummarySections,
  replaceAutoGeneratedBlock,
  writeMarkdownFile
} = require('./lib.ts');

const graph = JSON.parse(fs.readFileSync('generated/graph.json', 'utf8'));
const nodeByFile = new Map(graph.nodes.filter((node) => node.file).map((node) => [node.file, node]));
const sections = getVisualizationSummarySections();

const getSection = (prefix) => sections.find((section) => section.title.startsWith(prefix));
const secondPart = getSection('第二部分');
const toolEntries = (secondPart?.entries || []).filter((entry) => entry.filePath === 'part-2/chapter-4-claude-manual.md' || entry.filePath.startsWith('part-2/chapter-4-'));
const selectionEntries = (secondPart?.entries || []).filter((entry) => !toolEntries.some((item) => item.filePath === entry.filePath));

const layers = [
  {
    label: 'L1 认知层',
    entries: getSection('第一部分')?.entries || [],
    question: 'AI 编程到底改变了什么，Agent 与传统工具有何本质差异',
    output: '统一术语与认知边界'
  },
  {
    label: 'L2 工具层',
    entries: toolEntries,
    question: '如何稳定使用 Claude Code（命令、上下文、技能、GitHub 集成、工具设计）',
    output: '标准化工具使用规范'
  },
  {
    label: 'L3 选型层',
    entries: selectionEntries,
    question: '不同模型和产品在真实任务里如何取舍与组合',
    output: '多工具选型框架'
  },
  {
    label: 'L4 工程层',
    entries: getSection('第三部分')?.entries || [],
    question: '如何把提示工程、测试调试、项目实战连成闭环',
    output: '可验证的交付流程'
  },
  {
    label: 'L5 系统层',
    entries: getSection('第四部分')?.entries || [],
    question: '如何构建可扩展的 Agent 系统（构建、模式、多智能体、工作流、框架）',
    output: 'Agent 架构原型'
  },
  {
    label: 'L6 组织层',
    entries: getSection('第五部分')?.entries || [],
    question: '如何从个人提效走向团队级交付与治理',
    output: '组织级演进路线图'
  },
  {
    label: 'L7 支撑层',
    entries: getSection('附录')?.entries || [],
    question: '如何维持持续学习与外部知识更新',
    output: '资源索引与更新机制'
  }
].filter((layer) => layer.entries.length > 0);

function buildRefMap(entries) {
  const baseRefs = entries.map((entry) => extractChapterRef(entry.title));
  const counts = new Map();
  baseRefs.forEach((ref) => counts.set(ref, (counts.get(ref) || 0) + 1));

  return new Map(entries.map((entry) => {
    const baseRef = extractChapterRef(entry.title);
    if ((counts.get(baseRef) || 0) === 1) return [entry.filePath, baseRef];

    const suffixSource = entry.title.split(/[:：]/).slice(1).join(':').trim() || entry.sectionTitle;
    const suffix = suffixSource.split(/[——-]/)[0].trim().slice(0, 8);
    return [entry.filePath, `${baseRef}（${suffix}）`];
  }));
}

function inferTags(entry, node) {
  const tags = [];
  const title = entry.title;
  const layer = (node?.metadata?.architecture_layer || [])[0];

  if (layer === 'foundations') tags.push('research');
  if (layer === 'models-and-tools') tags.push('tooling');
  if (layer === 'workflows-and-practices') tags.push('workflow');
  if (layer === 'systems-and-governance') tags.push('system', 'org');
  if (entry.filePath.startsWith('appendix/')) tags.push('research');

  if (/(Prompt|上下文|Workflow|测试|调试|实战|复盘)/.test(title)) tags.push('workflow');
  if (/(Agent|系统|架构|Trellis|Harness|治理)/.test(title)) tags.push('system');
  if (/(组织|团队|复盘|怀疑者|Codex 的威力)/.test(title)) tags.push('org');

  return Array.from(new Set(tags)).slice(0, 3);
}

const allEntries = layers.flatMap((layer) => layer.entries);
const refMap = buildRefMap(allEntries);
const overviewRows = layers.map((layer) => [
  layer.label,
  layer.entries.map((entry) => refMap.get(entry.filePath)).join('、'),
  layer.question,
  layer.output
]);

const exactListLines = layers.flatMap((layer) => [
  `- **${layer.label}**：${layer.entries.map((entry) => refMap.get(entry.filePath)).join('、')}。`
]);

const chapterRefs = allEntries.map((entry) => refMap.get(entry.filePath));
const chapterRows = allEntries.map((entry) => {
  const node = nodeByFile.get(entry.filePath);
  return [refMap.get(entry.filePath), inferTags(entry, node).map((tag) => `\`${tag}\``).join(', ')];
});

const matrixRows = layers.map((layer) => {
  const refs = new Set(layer.entries.map((entry) => refMap.get(entry.filePath)));
  return [layer.label, ...chapterRefs.map((ref) => (refs.has(ref) ? '●' : ''))];
});

const autoBlockLines = [
  '## 内容架构分层（从知识到系统）',
  '',
  ...formatMarkdownTable(['架构层', '对应章节（精确清单）', '核心问题', '输出物'], overviewRows),
  '',
  '## 每层精确章节清单（便于增量维护）',
  '',
  ...exactListLines,
  '',
  '## 章节标签索引（自动推断）',
  '',
  '> 标签体系沿用原始可视化页的 `tooling`、`workflow`、`system`、`org`、`research`，当前按章节分层与标题关键词自动推断。',
  '',
  ...formatMarkdownTable(['章节', '主标签'], chapterRows),
  '',
  '## 章节索引矩阵（架构层 × 章节号）',
  '',
  '> 列为章节号，行为架构层。`●` 表示该章归属该层。',
  '',
  ...formatMarkdownTable(['架构层 \\ 章节号', ...chapterRefs], matrixRows),
  '',
  '## 跨层依赖关系',
  '',
  '1. L1 → L2：没有认知边界，工具实践容易陷入“提示词堆砌”。',
  '2. L2 → L4：工具熟练度决定工程化实践（测试、调试、实战）的上限。',
  '3. L3 ↔ L4：选型影响工程效率，工程反馈反过来修正选型策略。',
  '4. L4 → L5：只有形成交付闭环，才具备构建复杂 Agent 系统的基础。',
  '5. L5 → L6：系统能力是组织级自动化与自主代码库的前提。',
  '6. L7 贯穿 L1-L6：附录提供持续更新的参考基线。',
  '',
  '## 维护约束（避免索引失配）',
  '',
  '后续新增或调整章节时，必须在同一个 PR 内同步更新以下三处：',
  '',
  '1. `SUMMARY.md`（目录与链接）；',
  '2. `visualizations/timeline-overview.md`（原始时间线模式定义）；',
  '3. `visualizations/architecture-overview.md`（原始架构模式定义）。',
  ''
];

replaceAutoGeneratedBlock('visualizations/architecture-overview.md', 'ARCHITECTURE', autoBlockLines);

writeMarkdownFile('generated/architecture.md', [
  '# 内容架构总览（自动生成）',
  '',
  '> 本页与 `/visualizations/architecture-overview` 共享同一份自动生成内容。',
  '',
  '<ArchitectureVisualization />',
  '',
  ...autoBlockLines
]);

console.log('generated/architecture.md created');
